name: CI/CD Pipeline for Python Flask App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to checkout your repository code
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run simple Test
        run: |
          python -m unittest kraken_test.py
          echo "Tests passed successfully!"

      - name: Build and Push Docker Image
        run: docker build . -t ashishpandey2014/kraken:latest
      - name: Login to Docker Hub
        run: docker login -u ashishpandey2014 -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push image
        run: docker push ashishpandey2014/kraken:latest