name: CI/CD Pipeline for Python Flask App

on:
  [workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to checkout your repository code
      
      - name: Build and Push Docker Image
        run: docker build . -t ashishpandey2014/kraken:latest
      - name: push image
        run: docker login -u ashishpandey2014 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        run: docker push ashishpandey2014/kraken:latest
        